version: "3.8"

services:
  zaproxy:
    image: zaproxy/zap-stable
    container_name: zaproxy
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: >
      zap.sh -daemon
      -host 0.0.0.0
      -port 8080
      -config api.key=workshopzapapikey
      -config api.addrs.addr.name=".*"
      -config api.addrs.addr.regex=true
